### ISSUE TITLE
github linked demo times out

### ISSUE THREAD

**Issue by marcurdy** [sandialabs/scot#42]
Your link to the demo at https://52.12.122.162/ is unavailable.

**Comment by angeorgieff** [comment]
Mark,

Thanks for pointing that out. You can get to the current demo by going to
https://scotdemo.com.

We will update the readme.


On Jul 31, 2017 1:16 PM, "Mark McCurdy" <notifications@github.com> wrote:

Your link to the demo at https://52.12.122.162/ is unavailable.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sandialabs/scot/issues/42>, or mute the thread
